config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  devise_for :users
	

	get '/'          => 'welcome#index',  as: 'root_user'
	get '/users/:id' => 'welcome#show', 	as: 'user_profile'
	get 'jobs/personal/:name' => 'jobs#show' 


	resources :boats
	resources :jobs

    resources :jobs do

    member do
        get 'check'
    end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord

  belongs_to :user

  has_and_belongs_to_many :jobs

  	has_attached_file :avatar,
 	:styles => { :medium => "300x300>", :thumb => "150x150>" },
 	:default_url => "/images/no_image.png"

	validates_attachment_content_type :avatar,
 	:content_type => /\Aimage\/.*\Z/

 	geocoded_by :location
 	after_validation :geocode
 	

end

app/models/job.rb
class Job < ApplicationRecord

has_and_belongs_to_many :boats
belongs_to :user

geocoded_by :destination
 	after_validation :geocode

validates :price, length: {in: 4...100}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :jobs     
    has_many :boats
	has_attached_file :avatar,
 	:styles => { :medium => "300x300>", :thumb => "200x200>" },
 	:default_url => "/images/missing.png"

	validates_attachment_content_type :avatar,
 	:content_type => /\Aimage\/.*\Z/
 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :jobt

	def jobt
    
		if current_user


    @lastjob = Job.where(user_id: current_user.id)
    @lastboat = Boat.where(user_id: current_user.id)
    end
     
	end


   	def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :username, :dob, :gender, :user_type, :email, :password, :password_confirmation, :remember_me, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :username, :dob, :gender, :user_type, :email, :password, :password_confirmation, :remember_me, :avatar])
 			
   end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  
  def index
  	# to do: display all boats 
  	@boats = Boat.all 
  end

  def new
  	# to do: form to create new boats with location
  	@boat = Boat.new
  end

  def create
  	@boat = Boat.new(boat_params)
  	@user = User.find_by_id(current_user.id)
  	p @boat
  	@boat.user = @user
  	if @boat.save
  		redirect_to boats_path
		end
  end

  def edit
  	# to do: make form to assign boats to jobs
  	@boat = Boat.find(params[:id])
  end

  def update
  	@boat = Boat.find(params[:id])
  	@boat.update({
  		name: params[:boat][:name],
  		location: params[:boat][:location],
  		container: params[:boat][:container]
  	})
  	if (@boat)
  		redirect_to url_for(:controller => :boats, :action => :index)
  	else
  		redirect_to url_for(:controller => :boats, :action => :edit)
  	end
  end

  def show
  	# to do: be able to show a single boat and its job or availability
  	@boat = Boat.find(params[:id])
    @job = Job.first
  end

  def destroy
    # to do: be able to delete a boat from all boats collection
    @boat = Boat.find(params[:id])   
    @boat.destroy
    if @boat 
      redirect_to url_for(:controller => :boats, :action => :index)
    end
  end

  private

  def boat_params
  	params.require(:boat).permit(:name, :location, :container, :avatar)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
     # to do: display all jobs 
    @jobs = Job.all
    @user = User.find(current_user.id)
    @job = @user.jobs
    # if @job != nil
    #   # @job_current = Job.find(params[:job_id])
    # end
    @jobs = Job.where(user_id: current_user.id)
  end

  def new
    @job = Job.new
  end


def create
 @boat = Boat.find_by(name: params[:selected])
 @user = User.find_by_id(current_user.id)
 @job = Job.new(job_params)
 @job.user = @user
 @job.save
 @boat.jobs << @job
  if @job.save
   redirect_to '/jobs'
  end
end


  def edit
    @job = Job.find(params[:id])
  end

  def update
    @user = User.find_by_id(current_user.id)
    @job = Job.find(params[:id]).update(job_params)
    redirect_to url_for(:controller => :jobs, :action => :index)
  end

  def show
    # to do: be able to show a single boat and its job or availability
    
  


  if Job.find(params[:id])
    @job = Job.find(params[:id])

# @job = @j.select {|x| x.id == 1}
   @job_boat = @job.boats
    puts @job
    @boat = Boat.where(user_id: current_user.id)
   
 else
  redirect_to '/jobs'
end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to '/jobs'
  end


def check
@origin = params[:origin]
   
@boats = Boat.where(location: @origin)
respond_to do |format|
    format.html
    format.json {render json: @boats}
  end

end


private

def job_params
  	params.require(:job).permit(:name, :description, :origin, :destination, :container, :price)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = current_user

  end

  def show
  	@user = current_user

  end

  def edit
  	@user = current_user
  	params[:id] = current_user.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 def resource_name
   :user
 end

 def resource_class 
    User 
 end

 def resource
   @resource ||= User.new
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end

end

app/helpers/boat_helper.rb
module BoatHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boats/edit.html.erb
<% if current_user.user_type == "Shipping" %>

	<h2> Update your information: </h2>
	

<div class="formField">
	<%= form_for @boat do |f| %> 
		<br><%= f.label :name %>: <br>
		<%= f.text_field :name %> <br>
		<%= f.label "Number of Containers" %>: <br>
		<%= f.text_field :container %> <br>
		<%= f.label :location %>: <br>
		<%= hidden_field_tag 'user', 2 %><br>
		<%= f.select :location, [["Thor's Well, Oregon, USA", "Thor's Well, Oregon, USA"], ["The Bermuda Triangle, North Atlantic Ocean", "The Bermuda Triangle, North Atlantic Ocean"], ["Whale Bone Alley, Siberia", "Whale Bone Alley, Siberia"], ["The Giant's Causeway, Northern Ireland", "The Giant's Causeway, Northern Ireland"], ["Hvitserkur, Northern Iceland", "Hvitserkur, Northern Ireland"], ["Algarve, Portugal", "Algarve, Portugal"], ["Rio de Janiero, Brazil", "Rio de Janeiro, Brazil"], ["Galapagos Islands, Ecuador", "Galapagos Islands, Ecuador"], ["Queensland, Australia", "Queensland, Australia"], ["Benoa (Bali), Indonesia", "Benoa (Bali), Indonesia"], ["New York, NY, USA", "New York, NY, USA"], ["New Haven, CT, USA", "New Haven, CT, USA"]] %> <br>
		<br>
	<br>
		<%= f.submit "Update Boat" %>
	<% end %>
</div>

<% else %>

	<h1>Error: You do not have access to view this page</h1>

<% end %>

app/views/boats/index.html.erb
<% if current_user.user_type == "Shipping" %>

<div class="indexForm">
<h2 id="indexTitle"> View All Boats Here </h2>
<%=link_to 'Add new', new_boat_path(), :class=>"btn-success btn btn-github" %><br>
<% @boats.each do |boat| %>
	<div class="formFields">
			<br> Name: <%= boat.name %> <br><br>
					Location: <%= boat.location %> <br><br>
					Available Containers: <%= boat.container %><br><br>		
		<%= image_tag boat.avatar.url(:thumb) %><br>
		<a href="boats/<%= boat.id%>">View This Ship</a>
	</div>
<% end %>

</div>



<% else %>

	<h1>Error: You do not have access to view this page</h1>

<% end %>

app/views/boats/new.html.erb
<% if current_user.user_type == "Shipping" %>

	<%= form_for @boat, html: {multipart: true} do |f| %>
	<div class="formField">
		
		<%= f.label :name %>: <br>
		<%= f.text_field :name %> <br>
		<%= f.label "Number of Containers" %>: <br>
		<%= f.text_field :container %> <br>
		<%= f.label :location %>: <br>
		<%= hidden_field_tag 'user', 2 %>
		<%= f.select :location, [["Thor's Well, Oregon, USA", "Thor's Well, Oregon, USA"], ["The Bermuda Triangle, North Atlantic Ocean", "The Bermuda Triangle, North Atlantic Ocean"], ["Whale Bone Alley, Siberia", "Whale Bone Alley, Siberia"], ["The Giant's Causeway, Northern Ireland", "The Giant's Causeway, Northern Ireland"], ["Hvitserkur, Northern Iceland", "Hvitserkur, Northern Ireland"], ["Algarve, Portugal", "Algarve, Portugal"], ["Rio de Janiero, Brazil", "Rio de Janeiro, Brazil"], ["Galapagos Islands, Ecuador", "Galapagos Islands, Ecuador"], ["Queensland, Australia", "Queensland, Australia"], ["Benoa (Bali), Indonesia", "Benoa (Bali), Indonesia"], ["New York, NY, USA", "New York, NY, USA"], ["New Haven, CT, USA", "New Haven, CT, USA"]] %> <br>
		<br>
		<%= f.file_field :avatar %> <br>
	</div>
		<%= f.submit "Create New Boat" %>
	<% end %>

<% else %>

	<h1>Error: You do not have access to view this page</h1>

<% end %>

app/views/boats/show.html.erb
<% if current_user.user_type == "Shipping" %>

<% content_for :title, "Boat - " + @boat.name %>
<div class="row" id="widen">
	<div class="col-md-12">
		<div class="showField">
			Name: <%= @boat.name %><br>
			Location: <%= @boat.location %><br>
			Container Capacity: <%= @boat.container %><br/><br/>
			<%=link_to 'Edit', edit_boat_path(params[:id]), :class=>"btn-success btn btn-github" %>
			<%= link_to 'Delete',  { action: :destroy, id: @boat.id }, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-success btn btn-github" %>
			<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@boat.latitude},#{@boat.longitude}&markers=#{@boat.latitude},#{@boat.longitude}&zoom=7&size=500x242&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
		              class: 'img-fluid img-rounded', alt: "#{@boat.location} on the map", id:"map" %><br><br>

		</div>
	</div>
</div>

<% else %>

<h1>Error: You do not have access to view this page</h1>

<% end %>

app/views/jobs/index.html.erb
	
<% if current_user.user_type == "Job" %>

<h2>Available Jobs</h2>

<% if !@job.empty? %>
<%=link_to 'Add new', new_job_path(), :class=>"btn-success btn btn-github" %><br><br>
	<h2>All Jobs</h2>
	<% @jobs.reverse.each do |j|%>
		Job Title: <%= j.name %> <br>
		Description: <%= j.description %> <br>
		Origin: <%= j.origin %> <br>
		Destination: <%= j.destination %> <br>
		Container Count: <%= j.container %> <br>
		Price: <%= j.price %> <br/><br/>
		<a class="btn-success btn btn-github" href="/jobs/<%= j.id%>">View Job</a><br><br>
	<% end %>
<% else %>
		<h4>You have not logged any jobs</h4>

		<%=link_to 'Add new', new_job_path(), :class=>"btn-success btn btn-github" %><br><br>
		<h2>All Jobs</h2>
	<% end %>
<% else %>

<h1>Error: You do not have access to view this page</h1>

<% end %>

app/views/jobs/new.html.erb
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<% if current_user.user_type == "Job" %>



<h1><%=@message%></h1>


	<%= form_for @job do |f| %>
	<div class="formField">
		<%= f.label :name %>: <br>
		<%= f.text_field :name %> <br>
		<%= f.label :description %>: <br>
		<%= f.text_field :description %> <br>
		<%= f.label :origin %>: <br>
		<%= f.select :origin, [["Thor's Well, Oregon, USA", "Thor's Well, Oregon, USA"], ["The Bermuda Triangle, North Atlantic Ocean", "The Bermuda Triangle, North Atlantic Ocean"], ["Whale Bone Alley, Siberia", "Whale Bone Alley, Siberia"], ["The Giant's Causeway, Northern Ireland", "The Giant's Causeway, Northern Ireland"], ["Hvitserkur, Northern Iceland", "Hvitserkur, Northern Ireland"], ["Algarve, Portugal", "Algarve, Portugal"], ["Rio de Janiero, Brazil", "Rio de Janeiro, Brazil"], ["Galapagos Islands, Ecuador", "Galapagos Islands, Ecuador"], ["Queensland, Australia", "Queensland, Australia"], ["Benoa (Bali), Indonesia", "Benoa (Bali), Indonesia"], ["New York, NY, USA", "New York, NY, USA"], ["New Haven, CT, USA", "New Haven, CT, USA"]], {}, :id => "locale"  %> <br>
		<%= f.label :destination %>: <br>
		<%= f.select :destination, [["Thor's Well, Oregon, USA", "Thor's Well, Oregon, USA"], ["The Bermuda Triangle, North Atlantic Ocean", "The Bermuda Triangle, North Atlantic Ocean"], ["Whale Bone Alley, Siberia", "Whale Bone Alley, Siberia"], ["The Giant's Causeway, Northern Ireland", "The Giant's Causeway, Northern Ireland"], ["Hvitserkur, Northern Iceland", "Hvitserkur, Northern Ireland"], ["Algarve, Portugal", "Algarve, Portugal"], ["Rio de Janiero, Brazil", "Rio de Janeiro, Brazil"], ["Galapagos Islands, Ecuador", "Galapagos Islands, Ecuador"], ["Queensland, Australia", "Queensland, Australia"], ["Benoa (Bali), Indonesia", "Benoa (Bali), Indonesia"], ["New York, NY, USA", "New York, NY, USA"], ["New Haven, CT, USA", "New Haven, CT, USA"]] %> <br>
		<%= f.label :container %>: <br>
		<%= f.text_field :container %> <br>
		<%= f.label :price %>: <br>
		<%= f.text_field :price %> <br>
		<%= hidden_field_tag 'selected', 'none', :id => "hidden"  %>
	</div>
		<%= f.submit "Create New Job" , :id => 'submit_job' %>
	<% end %>


<button id="target">Submit</button>
<form id = optjob>
<label for="select_boat">Select a Boat</label>
<select class="sel">
  

</select>
</form>

<script>

$(document).ready(function() {
$("#target").click(function() {
var option = $("#locale").val()
var arr = []
$.ajax({
  type:"GET",
  url: "<%= check_job_path(current_user.id) %>",
  dataType:"json",
  data: {origin: option},
  success:function(result){
   for(i = 0; i<result.length;i++) {
   		Object.keys(result[i]).forEach(function(c) {
		if(c == "name"){
    	var select = {val: i + 1, text: result[i][c]}
    	arr.push(select);
			}
		});
	}

$(".formField").hide();
$("#target").hide();
$("#submit_job").show();
$("#optjob").show();
$('#hidden').val(arr[0].text);

$(arr).each(function() {
 $('.sel').append($("<option>").attr('value',this.text).text(this.text).attr("name", "name"));
			});
		}//success bracket close
	}); //Ajax bracket close
}); //target/click bracket close

$('select').on('change', function (e) {
    var optionSelected = $("option:selected", this);
    var val = this.value
    // alert(val);
    // alert($('#hidden').val())
    $('#hidden').val(val) 
    // alert($('#hidden').val())
    
	});
});// document/ready bracket close
</script>

<% else %>

<h1>Error: You do not have access to view this page</h1>

<% end %>

app/views/jobs/show.html.erb
<% if current_user.user_type == "Job" %>
<div class="showField">
	<%if(@job)%>
	Job Title: <%= @job.name %><br>
	Description: <%= @job.description %><br>
	Origin: <%= @job.origin %><br>
	Destination: <%= @job.destination %> <br>
	Container Count: <%= @job.container %> <br>
	Price: <%= @job.price %> <br><br>
	<% @job_boat.each do |boat| %>
 Boat chosen: <%= boat.name %> <br><br>
 Container capacity: <%= boat.container %> <br><br>
 <%= image_tag boat.avatar.url(:thumb) %><br><br>
Distance: <%= Geocoder::Calculations.distance_between([boat.latitude, boat.longitude], [@job.latitude,@job.longitude]).round(2) %> miles <br><br>
<% end %>
<%end%>
	<%=link_to 'Edit', edit_job_path(params[:id]), :class=>"btn-success btn btn-github" %>
	<%= link_to 'Delete',  { action: :destroy, id: @job.id }, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-success btn btn-github" %>
</div>

<% else %>

<%if @boat %>
<%@boat.reverse.each do |b|%>

<h1> <%=b.name %> </h1>
<%end%>
<% end %>
<%end%>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shipped Group Project" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <% if signed_in? %>

  <% if current_user.user_type == "Job" %>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" style="font-size: 28px; color: #ffffff; font-family: 'Roboto', sans-serif;" href="/">mybib</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "My Jobs", jobs_path %></li>
            <li><%= link_to "Profile", '/users/personal'  %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>

<% else %>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" style="font-size: 28px; color: #ffffff; font-family: 'Roboto', sans-serif;" href="/">mybib</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "My Boats", boats_path  %></li>
            <li><%= link_to "Profile", '/users/:id'  %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>

<% end %>

<% else %>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" style="font-size: 28px; color: #ffffff; font-family: 'Roboto', sans-serif;" href="/">mybib</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <div class="pull-right nav-login">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <%= f.email_field :email, autofocus: true, placeholder: "E-mail" %>
              <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
              <%= f.submit "Login", :class => 'btn btn-github' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<% end %>

    <div class="container">
      <div class="row main-bar">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        <div class="col-lg-3">
          <div class="well sidebar-nav text-center jobsy">
            <!-- <h3>Recent jobs</h3> -->
          
        <% if user_signed_in? %>
          <%if current_user.user_type == "Job" %>
            <ul class="nav nav-list">
                <li class="nav-header joberugen">My Recent Jobs</li>
              <%@lastjob.reverse.each do |l| %>
                <li class="jobery" style="color: #000000"><%= link_to l.name, '/jobs/'+(l.id).to_s  %></li>
            <br/>
              <%end%>
            </ul>
                 <a href="/jobs"><button class="btn jobsy-more">View More</button></a>
            <%else%> 
            <ul class="nav nav-list">
                <li class="nav-header joberugen">My Recent Boats</li>
              <%@lastboat.reverse.each do |l| %>
                <li class="jobery" style="color: #000000"><%= link_to l.name, '/boats/'+(l.id).to_s  %></li>
            <br/>
              <%end%>
            </ul>
               <a href="/boats"><button class="btn jobsy-more">View More</button></a>
            <%end%>
        <%else%>
            <ul class="nav nav-list">
            <li class="nav-header joberugen">Please Login to View Jobs or Boat</li>
            </ul>
        <%end%>

          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->
      <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
          <p class="navbar-text pull-left" style="color: white; font-family: 'Roboto', sans-serif;">© mybib Corp. 1872-2016
            <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank" class="cc">Terms and Conditions</a>
          </p>
          <a href="https://github.com/erven1985/Shipped_Group_project" class="navbar-btn btn-success btn btn-github pull-right">
          <span class="glyphicon glyphicon-star"></span>Fork this on GitHub!</a>
        </div>
      </div>
    </div> <!-- /container -->




  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<% content_for :title, "Home" %>
 <% if user_signed_in? %>

<div class="row">
	<div class="col-md-12 text-center">
		<% if current_user.user_type == "Job" %>
		<h1 class="slogan">You have it. They ship it. <br> We all make money.</h1>
		<% else %>
		<h1 class="slogan">They have it. You ship it. <br> We all make money.</h1>
		<% end %>
	</div>
</div>

<% else %>
<div class="row">
	<div class="col-md-12 text-center">
		<h1 class="slogan"> Send it. Ship it. <br> We all make money.</h1>
	</div>
</div>
<div class="signup" id="notauser">
  	<h4><span>...Not a user? <%= link_to 'Sign Up Here', '/users/sign_up' %></span></h4>
</div>

<% end %>